 CREATE TABLE account(
      user_id serial PRIMARY KEY,
      username VARCHAR (50) UNIQUE NOT NULL,
      password VARCHAR (50) NOT NULL,
      email VARCHAR (355) UNIQUE NOT NULL,
      created_on TIMESTAMP NOT NULL,
      last_login TIMESTAMP
   );

 CREATE TABLE STUDENT(
      id serial PRIMARY KEY,
      first_name VARCHAR (50) NOT NULL,
      last_name VARCHAR (50) NOT NULL,
      email VARCHAR (355) UNIQUE NOT NULL,
      created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
   );

   CREATE SEQUENCE IF NOT EXISTS STUDENT_SEQ INCREMENT BY 1 MAXVALUE 10000 START WITH 100;

 CREATE TABLE ADDRESS(
      id serial PRIMARY KEY,
      student_id INTEGER not null,
      street VARCHAR (150)  NOT NULL,
      unit_no VARCHAR (50) NOT NULL,
      zip NUMERIC (10)  NOT NULL,
      city VARCHAR (100) NOT NULL,
      state VARCHAR (50) NOT NULL,
      created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
   );

   CREATE SEQUENCE IF NOT EXISTS ADDRESS_SEQ INCREMENT BY 1 MAXVALUE 40000 START WITH 100;

