spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/company
    username: serviceuser
    password: serviceuser
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: uofu
    hibernate:
      ddl-auto: update

